### ISSUE TITLE
Orleans 7.2.1

### ISSUE THREAD

**Issue by Da-Teach** [escendit/rabbitmq-dotnet-extensions#16]
Although I suspect you found this out as well, this package is not compatible with Orleans 7.2.1. It'll crash during startup with a MissingMethodException: Method not found: 'System.Threading.Tasks.ValueTask Orleans.Runtime.GrainReference.InvokeAsync(Orleans.Serialization.Invocation.IInvokable)'.

**Comment by snovak7** [comment]
Yes, one way to get around the problem is to use explicit version Microsoft.Orleans.Core to 7.2.1

But if you're using this outside of Orleans you need to register one service first, to support named services.

**Comment by snovak7** [comment]
I found the registration code

```c#
.TryAddSingleton(typeof(IKeyedServiceCollection<,>), typeof(KeyedServiceCollection<,>));
```

Works with `Microsoft.Orleans.Core` package
